import { KpiCards } from '../../features/admin/dashboard/components/kpi-cards.jsx'
import { EditorialGuide } from '../../features/admin/dashboard/components/editorial-guide.jsx'
import { ModerationTable } from '../../features/admin/moderation/components/moderation-table.jsx'

export function AdminDashboardPage({ metrics, reviews, users, onRefresh, onExport, ...feedProps }) {
  return <>
    <div className="page-heading"><div><span className="eyebrow">LA MÚSICA NOS REÚNE. EL CRITERIO NOS DEFINE.</span><h1>Dashboard <em>Administrativo</em></h1><p>Una mirada al pulso de Sonar. Cada opinión cuenta, cada reseña importa.</p></div><div className="profile-card"><span className="avatar profile-avatar">S</span><div><small>ESPACIO DE CURADURÍA</small><strong>Consola administrativa</strong><span><i className="status-dot" /> Vista de prueba</span></div></div></div>
    <KpiCards metrics={metrics} busy={feedProps.busy} error={feedProps.error} />
    <section className="queue-banner"><div className="queue-symbol" aria-hidden="true">≋</div><div><span className="eyebrow">TU CRITERIO HACE LA DIFERENCIA</span><h2>{feedProps.error ? 'La comunidad merece una buena escucha.' : `${metrics.pendingReviews} ${metrics.pendingReviews === 1 ? 'reseña espera' : 'reseñas esperan'} tu próxima escucha.`}</h2><p>Ayuda a que las buenas conversaciones encuentren su lugar.</p></div><a className="primary-button" href="#moderacion">Ir a moderación <span>↗</span></a></section>
    <div className="workspace-grid"><ModerationTable {...feedProps} reviews={reviews} users={users} compact /><aside className="side-stack"><section className="panel distribution"><div className="panel-heading"><h2>Cómo suena Sonar</h2><span>↗</span></div><p>Distribución de calificaciones</p><div className="rating-bars">{[5, 4, 3, 2, 1].map(rating => { const count = reviews.filter(review => Math.round(review.rating) === rating).length; return <div key={rating}><span>{rating} <b>★</b></span><meter min="0" max={Math.max(reviews.length, 1)} value={count} aria-label={`${rating} estrellas: ${count} reseñas`} /><small>{count}</small></div> })}</div><div className="panel-bottom"><span>RESEÑAS REGISTRADAS</span><strong>{reviews.length}</strong></div></section><EditorialGuide /><section className="panel tools-panel"><span className="eyebrow">TU MESA DE TRABAJO</span><button onClick={onExport} disabled={feedProps.busy || !!feedProps.error}>↓ Descargar reseñas en CSV <span>↗</span></button><button onClick={onRefresh} disabled={feedProps.busy}>↻ Actualizar información <span>↗</span></button></section></aside></div>
  </>
}
